version: '2'

services:
  api:
    environment:
      NODE_ENV: development
    entrypoint: /home/docker/startup.integration.sh
    networks:
      - default
      - backend_api
networks:
  backend_api:
    driver: bridge
