version: '2'

services:
  user:
    environment:
      NODE_ENV: test
    entrypoint: /home/docker/startup.test.sh
    volumes:
      - ./services/user/src/unit_coverage:/var/lib/app/unit_coverage
      - ./services/user/src/functional_coverage:/var/lib/app/functional_coverage
