# swagger configuration file

# values in the swagger hash are system configuration for swagger
swagger:
  mapErrorsToJson: true

# any other values in this file are just loaded into the config for application access...
